PROGRAMMING ASSIGNMENT 2

NORMALIZATION PROBLEM:

In [1]:
import numpy as np

X = np.random.rand(5, 5)

X_normalized = (X - X.mean()) / X.std()

np.save('X_normalized.npy', X_normalized)

print("Normalized 5x5 array:\n", X_normalized)


Normalized 5x5 array:
 [[-0.29774468  0.78180195 -0.63682005  1.59021611 -0.16615095]
 [-0.87931174 -1.72357182 -0.23152401 -1.98782768  1.57237139]
 [ 0.12716473  0.23764035 -0.47696648  0.99335899  0.65049194]
 [ 1.06766898 -1.05098283 -0.50560514 -1.13914406  0.5072567 ]
 [-0.96718349  1.43751996 -0.74084292  0.68291394  1.15527081]]


DIVISIBLE BY 3 PROBLEM:

In [2]:
squares = np.arange(1, 101) ** 2
A = squares.reshape(10, 10)

div_by_3 = A[A % 3 == 0]

np.save('div_by_3.npy', div_by_3)

print("Numbers divisible by 3:\n", div_by_3)


Numbers divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
