PROGRAMMING ASSIGNMENT 2

NORMALIZATION PROBLEM:

In [1]:
import numpy as np

In [2]:
X = np.random.rand(5, 5)

In [5]:
X_normalized = (X - X.mean()) / X.std()
X_normalized

array([[-1.75865226,  0.78391943, -1.64854631,  1.76981772, -1.32898178],
       [ 0.64831977,  0.22752327,  0.83643574,  0.83168847,  0.6335522 ],
       [ 0.99751462, -0.52014939, -1.60560934, -0.22815576, -0.04697781],
       [-0.20855209,  0.62411479, -0.65303569,  0.8083092 ,  1.92337959],
       [-1.31605234, -0.44867486,  0.36185819, -0.38669218, -0.29635317]])

In [6]:
np.save('X_normalized.npy', X_normalized)

In [7]:
print("Normalized 5x5 array:\n", X_normalized)

Normalized 5x5 array:
 [[-1.75865226  0.78391943 -1.64854631  1.76981772 -1.32898178]
 [ 0.64831977  0.22752327  0.83643574  0.83168847  0.6335522 ]
 [ 0.99751462 -0.52014939 -1.60560934 -0.22815576 -0.04697781]
 [-0.20855209  0.62411479 -0.65303569  0.8083092   1.92337959]
 [-1.31605234 -0.44867486  0.36185819 -0.38669218 -0.29635317]]


DIVISIBLE BY 3 PROBLEM:

In [12]:
squares = np.arange(1, 101) ** 2

In [18]:
A = squares.reshape(10, 10)
A

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [15]:
div_by_3 = A[A % 3 == 0]

In [16]:
np.save('div_by_3.npy', div_by_3)

In [17]:
print("Numbers divisible by 3:\n", div_by_3)


Numbers divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
